name: Assign Random Reviewers

on:
  pull_request:
    types:
      - opened
      - reopened
    branches-ignore:
      - main

jobs:
  set-random-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Assign Random Reviewers
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 멤버 목록 (PR 작성자를 제외)
            const members = ['iey704', 'yerimming', 'makeUgreat', 'jay-so', 'jiminseong'];

            // PR 작성자 제외
            const filteredMembers = members.filter(member => 
              member !== "${{ github.event.pull_request.user.login }}");

            // 무작위로 섞고 최대 3명 선택
            const randomReviewers = filteredMembers.sort(() => Math.random() - 0.5).slice(0, 3);

            // GitHub에 리뷰어 할당 및 코멘트 작성
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `@${randomReviewers.join(' @')} 코드 리뷰 부탁드립니다.🙏`
            });
            
            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              reviewers: randomReviewers
            });

